# Generated by Django 2.2 on 2019-05-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20190517_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
    ]
