# Generated by Django 2.2 on 2019-05-28 05:30

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=firstapp.models.image_folder)),
            ],
        ),
    ]
