# Generated by Django 2.2 on 2019-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190528_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default=True, upload_to='image_folder')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
