# Generated by Django 2.2 on 2019-05-28 11:01

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20190528_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to=firstapp.models.image_folder),
        ),
    ]
